### ISSUE TITLE
CLA appears as "not signed" when it is

### ISSUE THREAD

**Issue by albarivas** [salesforce/dr-cla#41] opened 2022-01-13 14:22 UTC
Hi, a contributor for developerforce organization is having this issues with CLA signing.

The issue is described ([here](https://github.com/developerforce/salesforce-slack-starter-kit/pull/40#issuecomment-1012140123)). You can see the error number that's reported by the CLA form when you click on "details", maybe you can find out what's happening using that number? 

Thank you.

**Comment by jamesward** [comment] 2022-01-13 19:58
It's been a while since I worked on this, and no longer have access to the production logs.  But a few things that other admins can check:
https://cla.salesforce.com/status/developerforce/salesforce-slack-starter-kit/pull/40
https://cla.salesforce.com/audit

The user can maybe check:
https://cla.salesforce.com/signed-cla

**Comment by albarivas** [comment] 2022-01-14 08:52
Thank you @jamesward, who are other admins? Is there anyone I should ping?

**Comment by jamesward** [comment] 2022-01-14 21:49
We can try: @justinharringa @interactivellama

**Comment by justinharringa** [comment] 2022-01-14 23:58
@jimjag do you know what the status of developerforce is for this?

**Comment by pozil** [comment] 2022-01-31 10:58
I believe that this issue is related to #39.
The bot is not using the right CLA form URL.

**Comment by albarivas** [comment] 2022-01-31 12:08
> I believe that this issue is related to #39. The bot is not using the right CLA form URL. Once users sign https://cla.salesforce.com/sign-cla, they can proceed.

The user already tried that and it didn't work @pozil --> https://github.com/developerforce/salesforce-slack-starter-kit/pull/40

**Comment by jimjag** [comment] 2022-01-31 12:26
This is due to the age of the bot and that Scala is a language with no real current support among the the current set of users. For these occasional issues, the problem is resolved by hand.

**Closed by jimjag** 2022-01-31 12:26 UTC
